### ISSUE TITLE
中断后继续训练

### ISSUE THREAD

**Issue by moergo** [ABadCandy/BaiDuBigData19-URFC#5]
你好，想请教您训练过程中暂定后如何继续训练。
Traceback (most recent call last):
  File "multimain.py", line 249, in <module>
    main()
  File "multimain.py", line 178, in main
    checkpoint = torch.load(r'./checkpoints/best_models/seresnext101_dpn92_defrog_multimodal_fold_0_model_best_loss.pth.tar')
  File "/home/moer/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/best_models/seresnext101_dpn92_defrog_multimodal_fold_0_model_best_loss.pth.tar'

**Comment by ABadCandy** [comment]
@moergo 抱歉现在才看到，可以把multimain.py中第176行的resume设置为True, 然后178行load中断前保存的最新的.tar格式的模型权重应该就行了

**Comment by moergo** [comment]
嗯嗯，谢谢您了




------------------ 原始邮件 ------------------
发件人: "Hao Tang"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 晚上8:31
收件人: "ABadCandy/BaiDuBigData19-URFC"<BaiDuBigData19-URFC@noreply.github.com>;
抄送: "911086377"<911086377@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ABadCandy/BaiDuBigData19-URFC] 中断后继续训练 (#5)




@moergo 抱歉现在才看到，可以把multimain.py中第176行的resume设置为True, 然后178行load中断前保存的最新的.tar格式的模型权重应该就行了
