### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Ggmatch** [ABadCandy/BaiDuBigData19-URFC#6]
大神，我比较关注数据预处理部分，请问预处理（去全黑、全白等）部分在哪个代码文件里呀？

**Comment by ABadCandy** [comment]
抱歉，因为比赛还没结束，所以预处理和后处理部分代码目前还不打算全部放出来，暂时只能提供一些个人思路，在我的实验中对图像做去雾操作效果还是比较好的，具体参考《Single Image Haze Removal Using Dark Channel Prior》，至于其他一些常规的数字图像处理方法也可一试。

**Comment by ABadCandy** [comment]
@Ggmatch 抱歉，因为比赛还没结束，所以预处理和后处理部分代码目前还不打算全部放出来，暂时只能提供一些个人思路，在我的实验中对图像做去雾操作效果还是比较好的，具体参考《Single Image Haze Removal Using Dark Channel Prior》，至于其他一些常规的数字图像处理方法也可一试。

**Comment by Ggmatch** [comment]
> @Ggmatch 抱歉，因为比赛还没结束，所以预处理和后处理部分代码目前还不打算全部放出来，暂时只能提供一些个人思路，在我的实验中对图像做去雾操作效果还是比较好的，具体参考《Single Image Haze Removal Using Dark Channel Prior》，至于其他一些常规的数字图像处理方法也可一试。

谢谢大佬，我已经实现了，谢谢大佬提供的思路。
